dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake
            - cmake-data
            - libblas-dev
            - liblapack-dev
      env:
        - MATRIX_EVAL="CC=/usr/bin/gcc-7 && \
                       CXX=/usr/bin/g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - cmake
            - cmake-data
            - libblas-dev
            - liblapack-dev
            - libiomp-dev
      env:
        - MATRIX_EVAL="CC=/usr/bin/clang-6.0 && \
                       CXX=/usr/bin/clang++-6.0 && \
                       CFLAGS=-fopenmp=libiomp5 && \
                       CXXFLAGS=-fopenmp=libiomp5"


before_install:
  - eval "${MATRIX_EVAL}"
  - which $CC
  - $CC --version
  - which $CXX
  - $CXX --version

install: true

script:
  # Run your build commands next
  - ./testing/travis.sh
