dist: trusty
language:
  - cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake
            - libblas-dev
            - liblapack-dev
      env:
        - MATRIX_EVAL="CC=/usr/bin/gcc-7 && CXX=/usr/bin/g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - cmake
            - libblas-dev
            - liblapack-dev
      env:
        - MATRIX_EVAL="CC=/usr/bin/clang-6.0 && CXX=/usr/bin/clang++-6.0"


before_install:
  - eval "${MATRIX_EVAL}"

install: true

script:
  # Run your build commands next
  - ./testing/travis.sh
